version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    groups:
      java-dependencies:
        patterns:
          - "*"
